<a href="https://colab.research.google.com/github/akashktesla/pytorch_testing/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
print(torch.__version__)

2.0.1+cu118


In [ ]:
_matrix = torch.tensor([[1,2],[3,4]])
_matrix

tensor([[1, 2],
        [3, 4]])

In [ ]:
T = torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]])
T

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [ ]:
255*torch.rand((3,4))


tensor([[  8.9923,  10.4039,  72.3029,  32.4265],
        [ 78.0168,  87.4361, 206.1010, 125.1019],
        [179.5314,  10.4429, 245.9880,  17.4631]])

In [ ]:
torch.zeros((3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
a = torch.tensor([1,2])
b = torch.tensor([[5,7],[2,9]])

In [ ]:
torch.matmul(a,b)

tensor([ 9, 25])

In [ ]:
x = torch.tensor([[1, 2],[3, 4],[5, 6]], dtype=torch.float32)
x

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [ ]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2,out_features=1) 
output = linear(x)
output

tensor([[1.5488],
        [3.8038],
        [6.0588]], grad_fn=<AddmmBackward0>)

In [ ]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {torch.max(x)}")
print(f"Mean: {x.type(torch.float32).mean()}")
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [ ]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [ ]:
tensor.type(torch.float16).dtype

torch.float16

In [ ]:
torch.stack([tensor,tensor],dim=1)

tensor([[10, 10],
        [20, 20],
        [30, 30],
        [40, 40],
        [50, 50],
        [60, 60],
        [70, 70],
        [80, 80],
        [90, 90]])

In [ ]:
tensor.reshape(1,1,9).squeeze()

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])